### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by DavidBuchanan314** [RootMyTV/RootMyTV.github.io#1]
- [x] Complete all the readme/docs TODOs
- [x] Add a FAQ section, maybe?
- [x] Final proofreading
- [x] Finalize exploit code - use final file paths, urls etc. (meta-todo: add TODOs for these... [DONE])
- [x] Add a note to index.html that this is a "pre-release", ask people not to share widely yet (to be removed after initial testing).
- [x] Delete the current RootMyTV.github.io  placeholder repo
- [x] Rename RootMyTV-WIP to RootMyTV.github.io 
- [x] Point the rootmy.tv domain at github pages, and configure the domain in the github settings.
- [x] Do a sanity-check test installation
- [ ] Do a GitHub "pre-release" tag (v0.9?)
- [x] Un-private the repo
- [x] Get a few people to test it.
- [x] Remove the pre-release note, do a v1.0 release tag
- [ ] Tell the world!

Additional:
- [x] Fix mobile site layout
- [x] Add note about reboots sometimes failing

**Comment by Informatic** [comment]
Screw that, we going live NOW!
